### ISSUE TITLE
Singularity on WSL2 does not properly support NVIDIA GPU

### ISSUE THREAD

**Issue by Markus92** [sylabs/singularity#657]
**Version of Singularity**
Singularity v3.9.6

**Describe the bug**
When using WSL2 on Windows 10 21H2, GPU support is passed to the Linux VM. Unfortunately this does not work correctly inside Singularity containers, giving an error that the OS blocks GPU access:
```
Singularity> nvidia-smi
Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system
```

WSL2 distro used is Ubuntu 20.04 LTS, I use the same distro natively quite a bit and Singularity works just fine there with GPU access. GPU access also works fine when not using Singularity.

**To Reproduce**
Install a version of Windows which supports WSL2 with GPU passthrough (Windows 11 or 10 21H2+)
Install a Linux distro from the Windows store (I know, the irony...) which supports GPU passthrough, like Ubuntu 20.04
Confirm that `nvidia-smi` works fine outside of any container (or test with some deep learning libraries like PyTorch)
Compile and install Singularity, grab a container (like `singularity shell docker://nvidia/cuda:11.6.0-devel-ubuntu20.04`)
Run `nvidia-smi` and confirm that GPU access is blocked. Run a tool or library capable of utilizing the GPU and confirm it does not.

Note: my singularity.conf always binds nvidia libs.

**Expected behavior**
Container runs the same under WSL2 as it does natively.

**OS / Linux Distribution**
Windows 21H2 w/ WSL2 (kernel xx, NVidia driver 511.79, cuda 11.6 on host).
Linux distro: Ubuntu 20.04.4 LTS

**Installation Method**
From source, I can post detailed instructions if necessary.

**Additional context**
I know this is a very specific and unusual setup, but it would really help my development if we could make this work :) The beauty of singularity is that we can grab a container in .sif format and have deterministic results across all kinds of platforms and setups.

**Comment by dtrudg** [comment]
GPU in WSL2 isn't something we are actively supporting or testing at present. However, please try using the new method of setting up GPUs in a container... the `--nvccli` flag. This calls out out to NVIDIA's `nvidia-container-cli` to do the GPU setup, and that tool has some WSL handling in it.

See: https://sylabs.io/guides/latest/user-guide/gpu.html#nvidia-gpus-cuda-nvidia-container-cli

**Comment by Markus92** [comment]
Thanks for your reply. While that does work, it only works when I run singularity as root user. Guess that's some weird permission issue as my user is in the video group and docker works fine without escalating permissions. But could very well be an issue on my end.

**Comment by dtrudg** [comment]
Are you running Docker inside WSL? The Docker daemon runs as root by default, so it's somewhat different that Singularity unless you are setup for a true rootless Docker install.

Would be interested in any information you can give r.e. what is happening when you run as non-root. SingularityCE uses a setuid container starter to escalate privilege, including what's necessary for nvidia-container-cli.

**Comment by Markus92** [comment]
That's a good question. I run docker inside WSL and it thus probably runs as root (complete fresh vanilla install).

I have some logfiles for you. Here's the non-working log:
```
mark@Mark:~$ singularity -vvvvvv shell nnUNet_rcbftv.sif
VERBOSE: 'always use nv = yes' found in singularity.conf
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
VERBOSE: Setting HOME=/home/mark
VERBOSE: Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VERBOSE: Set messagelevel to: 4
VERBOSE: Starter initialization
VERBOSE: Check if we are running as setuid
VERBOSE: Drop root privileges
VERBOSE: Drop root privileges permanently
VERBOSE: Spawn stage 1
VERBOSE: Execute stage 1
VERBOSE: stage 1 exited with status 0
VERBOSE: Get root privileges
VERBOSE: Change filesystem uid to 1000
VERBOSE: Spawn master process
VERBOSE: Create mount namespace
VERBOSE: Entering in mount namespace
VERBOSE: Create mount namespace
VERBOSE: Spawn RPC server
VERBOSE: Execute master process
VERBOSE: Serve RPC requests
VERBOSE: Default mount: /proc:/proc
VERBOSE: Default mount: /sys:/sys
VERBOSE: Default mount: /dev:/dev
VERBOSE: Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE: Found 'bind path' = /etc/hosts, /etc/hosts
VERBOSE: Found 'bind path' = /run/user, /run/user
VERBOSE: Default mount: /tmp:/tmp
VERBOSE: Default mount: /var/tmp:/var/tmp
VERBOSE: Default mount: /etc/resolv.conf:/etc/resolv.conf
VERBOSE: Checking for template passwd file: /usr/local/var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE: Creating passwd content
VERBOSE: Creating template passwd file and appending user data: /usr/local/var/singularity/mnt/session/rootfs/etc/passwdVERBOSE: Default mount: /etc/passwd:/etc/passwd
VERBOSE: Checking for template group file: /usr/local/var/singularity/mnt/session/rootfs/etc/group
VERBOSE: Creating group content
VERBOSE: Default mount: /etc/group:/etc/group
VERBOSE: Not mounting CWD, while getting XXXX information: stat /usr/local/var/singularity/mnt/session/final/XXX: permission denied
FATAL:   container creation failed: nvidia-container-cli failed with exit status 1: nvidia-container-cli: permission error: capability change failed: operation not permitted
mark@Mark:
```

Here is it as root:
```
mark@Mark:~$ sudo singularity -vvvvvv shell nnUNet_rcbftv.sif
VERBOSE: 'always use nv = yes' found in singularity.conf
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
VERBOSE: Setting HOME=/root
VERBOSE: Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VERBOSE: Set messagelevel to: 4
VERBOSE: Starter initialization
VERBOSE: Check if we are running as setuid
VERBOSE: Spawn stage 1
VERBOSE: Execute stage 1
VERBOSE: stage 1 exited with status 0
VERBOSE: Spawn master process
VERBOSE: Create mount namespace
VERBOSE: Entering in mount namespace
VERBOSE: Create mount namespace
VERBOSE: Spawn RPC server
VERBOSE: Serve RPC requests
VERBOSE: Execute master process
VERBOSE: Default mount: /proc:/proc
VERBOSE: Default mount: /sys:/sys
VERBOSE: Default mount: /dev:/dev
VERBOSE: Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE: Found 'bind path' = /etc/hosts, /etc/hosts
VERBOSE: Found 'bind path' = /run/user, /run/user
VERBOSE: Default mount: /tmp:/tmp
VERBOSE: Default mount: /var/tmp:/var/tmp
VERBOSE: Default mount: /etc/resolv.conf:/etc/resolv.conf
VERBOSE: Not updating passwd/group files, running as root!
VERBOSE: Not mounting CWD, XXX doesn't exist within container
VERBOSE: Not mounting CWD, while getting XXX information: stat /usr/local/var/singularity/mnt/session/final/XXX: no such file or directory
VERBOSE: rpc server exited with status 0
VERBOSE: Execute stage 2
Singularity>
```
Nothing really in there I'm afraid that can explain it from what I can see right now. Any suggestion on what I could do for diagnostics?

**Comment by dtrudg** [comment]
"Borrowed" the family PC / gaming laptop to verify it does work with the patch above.

Can successfully run tensorflow/tensorflow:latest-gpu from Docker Hub and some perform model training with the GPU. In this case it's with Windows 11, WSL2, latest NVIDIA driver on Windows, and latest libnvidia-container-utils package in the Ubuntu WSL2 environment. RTX3060 GPU.

**Comment by Markus92** [comment]
Confirming it works perfectly now. Thanks for the quick follow-up and fix!
